#!/bin/bash

test_file()
{
  echo "Test" $1".moz"
  ../bin/moz --libpaths=../library/ ../demo/$1".moz" > test.out
  diff test.out "expected-output-"$1".txt"

}
   
test_file "modelica-mechsys" 

test_file "breaking-controlsys"
# test_file "breakingpendulum"
test_file "capacitor-switch"
test_file "controlsys"
test_file "hybrid-ball-stairs"
test_file "lotkavolterra"
test_file "pendulum"
# test_file "simpleresistorswitch"
test_file "synchronous"
test_file "timer"
test_file "very-fast-fly"

rm -f test.out
