#!/bin/bash
./moz lrd_igu.moz > lrd1.dat
mv lrd1.dat ../../MThesis/
./moz lrd_igu2.moz > lrd2.dat
mv lrd2.dat ../../MThesis/
./moz clutch_igu.moz > clutch.dat
mv clutch.dat ../../MThesis/
./moz lcd_igu.moz > diode.dat
mv diode.dat ../../MThesis/
./moz bounce2_igu.moz > bounce.dat
mv bounce.dat ../../MThesis/

