#!/bin/bash
./moz flybackdiode.moz > lrd1.dat
mv lrd1.dat ../../MThesis/
./moz flybackdiode2.moz > lrd2.dat
mv lrd2.dat ../../MThesis/
./moz clutch.moz > clutch.dat
mv clutch.dat ../../MThesis/
./moz diode.moz > diode.dat
mv diode.dat ../../MThesis/
./moz bounce.moz > bounce.dat
mv bounce.dat ../../MThesis/

