#!/bin/bash

test_local_file()
{
  echo "Test" $1".moz"
  ../bin/moz --libpaths=../library/ $1".moz" > test.out
  diff test.out "testdata/"$1".txt"
}

test_local_file "bounce"
test_local_file "clutch"
test_local_file "diode"
test_local_file "flybackdiode"
test_local_file "lc"
test_local_file "lr"
test_local_file "pendulum"
rm -f test.out
