type id =
    LEX_UNKNOWN_CHAR
  | LEX_STRING_NOT_TERMINATED
  | LEX_INVALID_ESCAPE
  | LEX_COMMENT_NOT_TERMINATED
  | LEX_UNKOWN_PRIMITIVE
  | LEX_UNKNOWN_FUNCTION
  | PARSE_ERROR
  | TYPE_MISMATCH_IF_GUARD
  | TYPE_IF_EXP_DIFF_TYPE
  | TYPE_IF_EXP_LEV_MONOTONICITY
  | TYPE_LAM_VAR_LEV_MONOTONICITY
  | TYPE_LAM_EXP_LEV_MONOTONICITY
  | TYPE_VAR_NOT_DEFINED
  | TYPE_META_UP_ON_FREE_VAR
  | TYPE_META_DOWN_ON_FREE_VAR
  | TYPE_SYMAPP_MISSING_ARG
  | TYPE_APP_ARG_MISMATCH
  | TYPE_APP_ABS_MISMATCH
  | TYPE_APP_NO_FUNC_TYPE
  | TYPE_LET_REC_MISS_RET_TYPE
  | TYPE_LET_TYPE_DEF_MISMATCH
  | TYPE_LET_PARAM_LEV_MONOTONICITY
  | TYPE_LET_DEF_MONOTONICITY
  | TYPE_LET_PARAM_LEV_LOWER
  | TYPE_LET_DEF_LOWER
  | TYPE_LET_TM1_LOWER
  | TYPE_LET_TM2_LOWER
  | TYPE_METAUP_LEV_MONOTONICITY
  | TYPE_METADOWN_LEV_STRICT_MONOTONICITY
  | TYPE_REL_OP_NOT_DEFINED
  | TYPE_FIX_MISMATCH
  | TYPE_FIX_ERROR
  | TYPE_REL_TYPE_PARAM_MISMATCH
  | TYPE_REL_LENGTH_MISMATCH
  | TYPE_REL_UNDEF
  | TYPE_REL_LEV_MONOTONICITY
  | TYPE_CONJ_DIFF_REL_LEV
  | TYPE_CONJ_LEV_MISMATCH
  | TYPE_CONJ_OP1_NOT_REL
  | TYPE_CONJ_OP2_NOT_REL
  | TYPE_UK_OP_NOT_REL
  | TYPE_UK_LEV_MISMATCH
  | TYPE_DESUGAR_ESC_LEV_ZERO
  | TYPE_NIL_LEV_MONOTONICITY
  | TYPE_CONS_TYPE_MISMATCH
  | TYPE_CONS_LEV_MONOTONICITY
  | TYPE_CONS_NOT_A_LIST
  | TYPE_LCASE_IDENTICAL_IDENTIFIERS
  | TYPE_LCASE_DIFFERENT_CASE_TYPES
  | TYPE_LCASE_LEVEL_MISMATCH
  | TYPE_LCASE_LEV_MONOTONICITY
  | TYPE_LCASE_MATCHING_TM_NOT_LIST_TYPE
  | TYPE_NU_LET_VAR_LEV_MONOTONICITY
  | TYPE_NU_LET_EXP_LEV_MONOTONICITY
  | TYPE_MODAPP_ARG_MISMATCH
  | TYPE_MODAPP_TYPE_MISMATCH
  | TYPE_EQUAL_EXP_DIFF_TYPE
  | TYPE_EQUAL_EXP_LEV_MONOTONICITY
  | TYPE_DECON_TYPE_NOT_MODEL
  | TYPE_DECON_LEV_MONOTONICITY
  | TYPE_DECON_MISMATCH
  | TYPE_TUPLE_LEV_MONOTONICITY
  | TYPE_PROJ_LEV_MONOTONICITY
  | TYPE_PROJ_TUPLE_SIZE
  | TYPE_PROJ_NOT_TUPLE
  | TYPE_DECON_PAT_UK_NOT_MODEL_TYPE
  | TYPE_MODEQUAL_NOT_CONCRETE_MODELTYPE
  | TYPE_MODIF_NOT_CONCRETE_MODELTYPE
  | TYPE_MODPROJ_NOT_MODELTUPLE
  | TYPE_ERROR_TERM_LEV_MONOTONICITY
  | TYPE_ERROR_TERM_NOT_STRING
  | TYPE_NU_LET_NOT_MODELTYPE
  | TYPE_UNKNOWN_TYPE
  | RUNTIME_ERROR
  | PATMATCH_UNUSED_PATTERN
  | PATMATCH_MIXING_PATTERN_TYPES
  | TYPE_MATCH_MONOTONICITY
  | TYPE_ARRAY_LEV_MONOTONICITY
  | TYPE_ARRAY_ELEM_NOT_CONSISTENT
  | TYPE_EXPECTED_ARRAY_TYPE
  | TYPE_EXPECTED_MAP_TYPE
  | TYPE_EXPECTED_SET_TYPE
  | TYPE_EXPECTED_DAESOLVER_TYPE
  | TYPE_EXPECTED_INT_TYPE
  | TYPE_EXPECTED_REAL_TYPE
  | TYPE_EXPECTED_CONSTANT_LEV
  | TYPE_UNEXPECTED_NO_ARGS
  | TYPE_EXPECTED_RESROOT_TYPE
  | TYPE_ERROR_TERM_NOT_SYM
  | STATIC_CIRCULAR_DEP_INCLUDE
  | STATIC_ERROR_OPEN_FILE
  | RUNTIME_TYPE_ERROR
type severity = ERROR | WARNING
type arguments = Ustring.Op.ustring list
type message = id * severity * Info.info * arguments
exception Mkl_lex_error of message
exception Mkl_static_error of message
val id2str : id -> Ustring.Op.ustring list -> Ustring.Op.ustring
val severity2str : severity -> Ustring.Op.ustring
val info2str_startline : Info.info -> Info.row
val message2str :
  id * severity * Info.info * Ustring.Op.ustring list -> Ustring.Op.ustring
